name: trigger workflow 
on:
    push:
        branches: ["develop"]
jobs:
    trigger: 
        runs-on: ubuntu-latest
# create a trigger that activates another workflow(the issue one)
        steps:
            - name: trigger another workflow
              run: |
                curl -X POST https://api.github.com/repos/${{ github.repository }}/actions/workflows/issue.yml/dispatches \
                -H 'Accept: application/vnd/github.v3+json' \
                --header 'Autorization: Bearer ${{ secrets.MySecret }}' \
                --data '{"ref": "${{github.ref}}"}'
                
    Slack:
       runs-on: ubuntu-latest                
       steps:
             - name: Slack Notifications
               uses: rtCamp/action-slack-notify@v2.0.1
               env:
                   SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
                   SLACK_CHANNEL: general
                   SLACK_TITLE: Build Sucess
                   SLACK_COLOR: '#43a047'
                   SLACK_MESSAGE: ${{ github.repository }} Build Success
                   SLACK_USERNAME: ${{ github.repository }}

            
